name: "Deploy to Render"
description: "Deploys the application to Render"
inputs:
  RENDER_API_KEY:
    description: "The API key for Render"
    required: true
  RENDER_SERVICE_ID:
    description: "The service ID for Render"
    required: true
runs:
  using: "composite"
  steps:
    - name: Debug Inputs
      run: |
        echo "RENDER_API_KEY: ${{ inputs.RENDER_API_KEY }}"
        echo "RENDER_SERVICE_ID: ${{ inputs.RENDER_SERVICE_ID }}"
      shell: bash

    - name: Check required secrets
      run: |
        if [ -z "${{ inputs.RENDER_API_KEY }}" ]; then
          echo "RENDER_API_KEY is missing"
          exit 1
        fi
        if [ -z "${{ inputs.RENDER_SERVICE_ID }}" ]; then
          echo "RENDER_SERVICE_ID is missing"
          exit 1
        fi
      shell: bash

    - name: Deploy to Render
      run: |
        RESPONSE=$(curl -X POST "https://api.render.com/v1/services/${{ inputs.RENDER_SERVICE_ID }}/deploys" \
           -H "Authorization: Bearer ${{ inputs.RENDER_API_KEY }}" \
           -H "Content-Type: application/json" \
           --data '{}' -w "%{http_code}" -o /dev/null)

         if [ "$RESPONSE" -ne 200 ] && [ "$RESPONSE" -ne 201 ]; then
           echo "Deployment failed with status code $RESPONSE"
           cat response.json
           exit 1
         fi
         echo "Deployment triggered successfully 🚀"
      shell: bash
      env:
        RENDER_API_KEY: ${{ inputs.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ inputs.RENDER_SERVICE_ID }}
